<?php if(count($this->banners)):?>
<?php echo $this->render('widget/header.phtml');?>
<div class="bem-widget-banners">
<?php foreach ($this->banners as $banner): ?>
    <div class="banner_box">
        <a href="<?php echo $banner['link'];?>"><img src="<?php echo $banner['src'];?>" alt="<?php echo $banner['alt'];?>"/></a>
    </div>
<?php endforeach;?>
</div>
<?php echo $this->render('widget/footer.phtml');?>
<?php endif;?>
