<?php echo $this->render('widget/header.phtml');?>
<div class="bem-widget-search_advanced">
    <form action="/search/">
        <div class="form_field field_profession" style="">
            <label>Профессии:</label>
            <div class="form_field-input_box"><input name="professions" type="text" value="<?php echo '';?>" class="" style=""/></div>
            <div class="form_field-tips"></div>
        </div>
        
    </form>
</div>
<?php echo $this->render('widget/footer.phtml');?>
