<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="bem-search_engine-admin" widget="se.controlPanel" itemsPerIteration="<?php echo OptionHelper_wpp_BRX_SearchEngine::getOption('items_per_iteration', 10);?>" style="display:none;">
    <table class="control_panel" cellspacing="0" rules="">
        <tr>
            <td>Тип записи</td>
            <td>Поиск</td>
            <td>Всего</td>
            <td>В индексе</td>
            <td>Управление</td>
        </tr>
    <?php foreach($this->postTypeInfo as $name => $postType): ?>    
        <tr class="<?php echo $name;?>">
            <td class="title"><?php printf('%s (%s)', $postType['label'], $name);?></td>
            <td class="switch"><?php echo $this->formSelect('searchEnabled.'.$name, $postType['enabled']?'1':'0', 
                    array(
                        'data-attach-point'=>'searchEnabled.'.$name, 
//                        'data-attach-event'=>'change: filterChanged'
                        ), 
                    array(
                        '1' => 'Вкл.',
                        '0' => 'Выкл.',
                    ));?></td>
            <td class="total" data-attach-point="cellTotal.<?php echo $name;?>"><?php echo $postType['total'];?></td>
            <td class="indexed" data-attach-point="cellIndexed.<?php echo $name;?>"><?php echo $postType['indexed'];?></td>
            <td class="actions">
                <span data-attach-point="linkCreateIndex.<?php echo $name;?>">Полная индексация</span>
                <span data-attach-point="linkUpdateIndex.<?php echo $name;?>">Обновить индекс</span>
                <span data-attach-point="linkDeleteIndex.<?php echo $name;?>">Удалить индекс</span>
            </td>
        </tr>
    <?php endforeach;?>
        <tr class="selected">
            <td class="title">Выбранные типы</td>
            <td class="switch"></td>
            <td class="total" data-attach-point="cellTotal.selected">0</td>
            <td class="indexed" data-attach-point="cellIndexed.selected">0</td>
            <td class="actions">
                <span data-attach-point="linkCreateIndex.selected">Полная индексация</span>
                <span data-attach-point="linkUpdateIndex.selected">Обновить индекс</span>
                <span data-attach-point="linkDeleteIndex.selected">Удалить индекс</span>
            </td>
        </tr>
    </table>
    <div class="processor" data-attach-point="boxProgress" style="display: none;">
        <div class="progressbar" widget="progressbar" attachwidget="progressbar">
            <div class="progresslabel" data-attach-point="progresslabel">100%</div>
        </div>
        <div class="progressspinner" widget="brx.spinner" attachwidget="progressSpinner"></div>
        <div class="boxOutput" data-attach-point="boxOutput">
            
        </div>
    </div>
    <script type="text/javascript">
        window.postTypeInfo = <?php echo JsonHelper::encode($this->postTypeInfo)?>;
    </script>
    <?php ZF_Core::addJQueryWidgets();?>
</div>