<?php


?>
<div class="wrap">
    <div id="icon-options-general" class="icon32">
        <br/>
    </div>
    <h2>Общие настройки Поисковой системы</h2>
    <?php echo $this->render('indexer/control-panel.phtml')?>
<?php
//    echo "Initial ";
//    print_r(SearchHelper::getSearchEnabledPostTypes());
//    echo "enable a ";
//    SearchHelper::enableSearch('a');
//    print_r(SearchHelper::getSearchEnabledPostTypes());
//    echo "enable b c ";
//    SearchHelper::enableSearch(array('b','c'));
//    print_r(SearchHelper::getSearchEnabledPostTypes());
//    echo "enable a ";
//    SearchHelper::enableSearch('a');
//    print_r(SearchHelper::getSearchEnabledPostTypes());
//    echo "enable b c ";
//    SearchHelper::enableSearch(array('b','c'));
//    print_r(SearchHelper::getSearchEnabledPostTypes());
//    echo "disable b ";
//    SearchHelper::disableSearch('b');
//    print_r(SearchHelper::getSearchEnabledPostTypes());
//    echo "disable a c ";
//    SearchHelper::disableSearch(array('a','c'));
//    print_r(SearchHelper::getSearchEnabledPostTypes());
//    echo "disable b ";
//    SearchHelper::disableSearch('b');
//    print_r(SearchHelper::getSearchEnabledPostTypes());
//    echo "disable b c ";
//    SearchHelper::disableSearch(array('b','c'));
//    print_r(SearchHelper::getSearchEnabledPostTypes());
?>
</div>